_16pawns/SixteenPawns/urls.py
'''validation file for every possible urls'''
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^game/(?P<pk>\d+)$', views.GameDetailView.as_view(), name='game'),
    url(r'^game/(?P<pk>\d+)/json', views.get_game_json, name='gameJson'),
    url(r'^rules$', views.rules, name='rules'),
    url(r'^usermanual$', views.usermanual, name='usermanual'),
    url(r'^signup$', views.SignupView.as_view(), name='signup'),
    url(r'^login$', views.LoginView.as_view(), name='login'),
    url(r'^logout$', views.LogoutView.as_view(), name='logout'),
    url(r'^new-game$', views.new_game, name='new_game'),
    url(r'^process_move$', views.process_move, name='process_move'),
    url(r'^invite-friend$', views.invite_friend, name='invite_friend'),
    url(r'^credits$', views.game_credits, name='credits'),
    url(r'^my-games$', views.UserGamesView.as_view(), name='game_list'),
    url(r'^leaderboard$', views.LeaderboardView.as_view(), name='leaderboard'),
]

_16pawns/_16pawns/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('SixteenPawns.urls')),
]

_16pawns/SixteenPawns/models.py
# -*- coding: utf-8 -*-
""" models.py """
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from jsonfield import JSONField
from django.contrib.auth.models import User

GAME_STATUS = (
    ('M', 'MatchingPlayers'),
    ('IP', 'InProgress'),
    ('GO', 'GameOver'),
    ('T', 'Terminated')
)

# Create your models here.
class Game(models.Model):
    """This model is the back bone for a game in the system as it requires 2
    players, board_data in the JSON (dictionary) format, winner, scores,
    current player's turn, and date."""
    player1 = models.ForeignKey(User, related_name='game1')
    player2 = models.ForeignKey(User, related_name='game2', null=True, blank=True)
    board_data = JSONField()
    status = models.CharField(default='M', max_length=2, choices=GAME_STATUS)
    winner = models.ForeignKey(User, related_name='games_won', null=True, blank=True)
    player1_score = models.IntegerField(default=0)
    player2_score = models.IntegerField(default=0)
    current_player = models.ForeignKey(User, related_name='turn', null=True, blank=True)
    date = models.DateField(default=datetime.now())


class OnlineUser(models.Model):
    """This model is used to keep track of online users"""
    user = models.ForeignKey(User, related_name='online')
    is_online = models.BooleanField(default=False)
    date = models.DateField(default=datetime.now())

_16pawns/SixteenPawns/forms.py
""" forms.py """
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class SignupForm(ModelForm):
    """ Signup Form """
    class Meta:
        """ meta """
        model = User
        fields = ['first_name', 'last_name', 'email', 'password']

    email_cn = forms.CharField(label='email_cn', max_length=100)
    password_cn = forms.CharField(label='password_cn', max_length=100)


    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        password_cn = self.cleaned_data.get("password_cn")

        if password != password_cn:
            error = ("Both passwords don't match")
            self.add_error('password', error)
        if User.objects.filter(email=email).exists():
            error = ("Email Address already exists!")
            self.add_error('email', error)

    def create_user(self):
        """ create new user """
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = User.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            username=email)

        user.set_password(password)
        user.save()

class LoginForm(ModelForm):
    """ login form """
    class Meta:
        model = User
        fields = ['email', 'password']

    def clean(self):
        # authenticate user
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = authenticate(username=email, password=password)
        self.user = user
        if user is None:
            # authentication failed: add error message
            error = 'Invalid email/password'
            self.add_error('email', error)

    def get_user(self):
        """ get user """
        return self.user

    def authenticate_user(self, request):
        """ authenticate user """
        # authenticate user
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        user = authenticate(username=email, password=password)
        if user is None:
            # authentication failed: add error message
            error = 'Invalid email/password'
            self.add_error('email', error)

_16pawns/SixteenPawns/views.py
# -*- coding: utf-8 -*-
""" views.py """
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic.edit import FormView
from django.views.generic.base import RedirectView
from django.contrib.auth import login, logout
from django.contrib import messages
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.db.models import Q, Count
from django.views.generic.list import ListView
from SixteenPawns.game_engine import handleMoveRequest, init_board
from SixteenPawns.forms import SignupForm, LoginForm
from SixteenPawns.models import Game


# Create your views here.

def index(request):
    '''creates request'''
    return render(request, 'index.html', context={})

def new_game(request):
    '''check if user is currently playing a game or not.'''
    earliest_game = Game.objects.filter(status='M').exclude(
        player1=request.user).first()
    if earliest_game is not None:
        # user joins an existing game
        # user is matched with the player that is first in the queue
        earliest_game.player2 = request.user
        earliest_game.status = "IP"
        earliest_game.save()
        game_id = earliest_game.id
    else:
        # create a new game
        board = init_board()
        game = Game.objects.create(
            player1=request.user,
            board_data=board,
            current_player=request.user,
        )
        game_id = game.id
    return redirect('game', pk=game_id)

def process_move(request):
    '''precess the valid move, if not decline it.'''
    game_id = request.GET["gameId"]
    user_id = request.GET["userId"]
    old_x = int(request.GET["old_x"]) + 1
    old_y = int(request.GET["old_y"]) + 1
    new_x = int(request.GET["new_x"]) + 1
    new_y = int(request.GET["new_y"]) + 1
    if handleMoveRequest(game_id, user_id, old_x, old_y, new_x, new_y):
        print "Valid Move"
    else:
        print "Not Valid"
    return redirect('game', pk=game_id)


def rules(request):
    '''show the rules page'''
    return render(request, 'rules.html', context={})

def usermanual(request):
    '''show the rules page'''
    return render(request, 'usermanual.html', context={})

class LogoutView(RedirectView):
    """ Logout """
    url = '/'

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

class SignupView(FormView):
    """ Sign up """
    template_name = 'signup.html'
    form_class = SignupForm
    success_url = '/'

    def form_valid(self, form):
        '''this method is called when a valid form of data has
            been posted, it would return an http request
        '''
        form.create_user()
        #print "valid"
        messages.success(self.request, 'Your account has been created.')
        return super(SignupView, self).form_valid(form)

    def form_invalid(self, form):
        '''shows invalid move sign'''
        #print "invalid"
        return super(SignupView, self).form_invalid(form)

class LoginView(FormView):
    """ Login """
    template_name = 'index.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form):
        '''this method is called when a valid form of data has
            been posted, it would return an http request
            get from form.authenticate_user
        '''
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)

def get_game_json(request, pk):
    '''get's the json data, and prints game_id'''
    game_id = pk
    print game_id
    game = Game.objects.get(pk=pk).board_data
    print "GAME", game
    return JsonResponse(game, safe=False)


class GameDetailView(DetailView):
    """ Game Detail View """
    model = Game
    template_name = 'game.html'

    def get_context_data(self, **kwargs):
        '''gets the context data, calls self.request.user, other wise return to the context'''
        pk = self.kwargs['pk']
        game = Game.objects.get(pk=pk)
        context = super(GameDetailView, self).get_context_data(**kwargs)
        context['board'] = game.board_data
        player_num = 2
        if game.player1 == self.request.user:
            player_num = 1
        context['player_num'] = player_num
        return context

def invite_friend(request):
    '''goto the invite friend page'''
    return render(request, 'invite.html', context={})

def game_credits(request):
    '''go to the credit page'''
    return render(request, 'credit.html', context={})

class UserGamesView(ListView):
    '''creates a game view from the client side'''

    model = Game
    template_name = 'game_list.html'

    def get_queryset(self):
        query = Game.objects.filter(
            Q(player1=self.request.user) |
            Q(player2=self.request.user)
        ).all()
        return query

class LeaderboardView(ListView):
    '''creates the leaderboard views'''

    model = Game
    template_name = 'leaderboard.html'

    def get_queryset(self):
        '''calls game.objects.annotate, shows who winned the game'''
        query = Game.objects.annotate(
            num_wins=Count('winner')).order_by('-num_wins').exclude(winner__isnull=True)[:10]
        return query

_16pawns/SixteenPawns/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap</title>-->

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">

    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/chat.js' %}" type="text/javascript"></script>
    <!-- Add IntroJs styles -->
    <link href="{% static 'intro.js-2.5.0/introjs.css' %}" rel="stylesheet">
          
    <script type="text/javascript" src="{% static 'intro.js-2.5.0/intro.js' %}"></script>


    {% block head_extra %}
    {% endblock %}

  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">16 Pawns</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}">Home</a></li>

            <li><a href="{% url 'rules' %}" data-step="2" data-intro="You can read the rules of the game here.">Rules</a></li>
            <li><a href="{% url 'usermanual' %}" data-step="7" data-intro="You can read more user documentation here.">User Manual</a></li>
            <li><a href="{% url 'leaderboard' %}" data-step="6" data-intro="Checkout the top 10 players with the most number of wins.">Leaderboard</a></li>
            {% if request.user.is_authenticated %}

              <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}

            {% endif %}
          </ul>
	  <!--{% if request.user.is_authenticated %}
          <ul style="float:right;" class="nav navbar-nav">
            <div id="main">
              <li><span onclick="openNavigation()" style="color:white; cursor:pointer">Chat &#9776;</span></li>
            </div>
            <div id="mySideNavigation" class="sideNavigation">
              <a class="closeButton" onclick="closeNavigation()">&times;</a>
              <div>
                <ul id="myMessages"></ul>
                <form id="myFormStyle" class="formStyle">
                  <input id="chat_input" type="text" autocomplete="off">
                  <button id="send_message" onclick="sendMessage()">Send</button>
                </form>
              </div>
            </div>
          </ul>
          {% endif %}-->
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      <br><br><br>
      <div class="row">


      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      {% block body %}
      {% endblock %}
      </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.js"></script>-->
    
    
    
    <script type="text/javascript">
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
         (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
         m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
         })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
         
         ga('create', 'UA-69239984-1', 'auto');
         ga('send', 'pageview');
        </script>
    
  </body>
</html>

_16pawns/SixteenPawns/templates/chat.html
{% load static %}

    <!DOCTYPE html>
    <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
            <meta name="description" content="" />
            <meta name="author" content="" />
            <!--[if IE]>
             <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
             <![endif]-->
            <title>Chat</title>
            
        </head>
        <body style="font-family:Verdana">
            <div class="container">
                <div class="row " style="padding-top:40px;">
                    <div class="col-md-8" data-step="5" data-intro="You can chat with people here.">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                CHAT ROOM
                            </div>
                            <div class="panel-body">
                                <ul class="media-list" id="group_chat" style="min-height:50px">
                                    
                                 </ul>
                            </div>
                            <div class="panel-footer" style="min-height:50px">
                                <div class="input-group">
                                    <input id="chat_message" type="text" class="form-control" placeholder="Enter Message" />
                                    <span class="input-group-btn">
                                        <button class="btn btn-info" type="button" onclick="sendMessage()">SEND</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4" data-step="4" data-intro="You can see a list of online users here.">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                ONLINE USERS
                            </div>
                            <div class="panel-body">
                                <ul class="media-list" id="online_users">
                                    
                                </ul>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <script>
                (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
                 
                 ga('create', 'UA-58126461-1', 'auto');
                 ga('send', 'pageview');
                 
                </script>
        </body>
    </html>

_16pawns/SixteenPawns/templates/credit.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Welcome to 16 pawns</title>

  <link href="style.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12 text-center">
			<h1>Credit</h1>
		</div>
	</div>

  
	<div class= "row">
		<div class="col-lg-12 text-center">
      			<h3><a href="mailto:isatousanneh14@hotmail.com">Isatou Sanneh</a> </h3><br>
      			<h3><a href="mailto:fahadu90@gmail.com">Fahad Uddin</a></h3><br>
      			<h3><a href="mailto:b.rosanlall@gmail.com">Bharat Rosanlall</a></h3><br>
      			<h3><a href="mailto:tpatrick1496@gmail.com">Vladimir Toussaint</a></h3>
		</div>
	</div>

	<div class="row">
 		<a class="w3-left w3-btn" href="{% url 'index' %}"> <h1>❮ Back to Menu </h1> </a>
	</div>

</html>

_16pawns/SixteenPawns/templates/game.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <div class="row" id="game"><br><br>
                {% include 'modal.html' %}
                <div class="col-sm-3">
                  <h2>Player 1<img src="{% static 'img/player1.png' %}" width="50px" height="50px"/></h2>
                  <h3 id="player1"> 
                    {% if game.player1 %} 
                      {{ game.player1.first_name }} 
                    {% else %} 
                      Waiting for first player to join. 
                    {% endif %}
                  </h3>
                  <h3 id="player1_turn"></h3>
                  <h3>Score: <span id="player1_score">{{ game.player1_score }}</span></h3>
                </div>
	  	<div class="col-sm-6">
                        <div id="alert" class="alert alert-success" role="alert">
                            Welcome {{ request.user.first_name }}
                        </div>
	   		<canvas id="canvas" width="450" height="700" style="border:2px solid #000000;">
	   		</canvas>
	  	</div>
                <div class="col-sm-3">
                  <h2>Player 2<img src="{% static 'img/player2.png' %}" width="50px" height="50px"/></h2>
                  <h3 id="player2"> 
                    {% if game.player2 %} 
                      {{ game.player2.first_name }} 
                    {% else %} 
                      Waiting for second player to join.
                    {% endif %}
                  </h3>
                  <h3 id="player2_turn"></h3>
                  <h3>Score: <span id="player2_score">{{ game.player2_score }}</span></h3>
                </div>
    </div>

  <script type="text/javascript">
    var game_id = {{ game.id }};
    var user_id = {{ request.user.id }};
    var player1_id = {{ game.player1.id }};
    {% if game.player2 %}
      var player2_id = {{ game.player2.id }};
    {% endif %}
    var current_player_id = {{ game.current_player.id }};
    var player_num = {{ player_num }};
    var status = '{{ game.status }}';
    var player1_score = {{ game.player1_score }};
    var player2_score = {{ game.player2_score }};
  </script>
    
  <!-- Note: Do not move this file to the top of the page. The click events for the board
       (i.e. keeping track of board postions clicked and moving pawns) only work if 
       it is placed at the bottom -->

  <script type="text/javascript"> 
    var django_board = (("{{game.board_data|safe}}").replace(/&(l|g|quo)t;/g, function(a,b){
      return{
        l : '<',
        g : '>',
        quo : '"'
      } [b];
    }));

    django_board = django_board.replace(/u'/g, '\'');
    django_board = django_board.replace(/'/g, '\"');

    board_json = JSON.parse(django_board);
  </script>
  


  <script src="{% static 'js/connect_game.js' %}"> </script>

  <script src="{% static 'js/16pawns.js' %}"> </script>
  <script>
    document.body.onload = Draw();
    //setInterval(refreshBoard,10000);
  </script>

<!--// socket communication
// Note that the path doesn't matter for routing; any WebSocket
// connection gets bumped over to WebSocket consumers
socket = new WebSocket("ws://" + window.location.host + "/chat/");
socket.onmessage = function(e) {
    //alert(e.data);
}
socket.onopen = function() {
    socket.send("hello world");
}
// Call onopen directly if socket is already open
if (socket.readyState == WebSocket.OPEN) socket.onopen();
-->

{% endblock %}

_16pawns/SixteenPawns/templates/game_list.html
{% extends 'base.html' %}
{% load static %}

{% block head_extra %}
  <title>Welcome to 16 pawns</title>

  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">

{% endblock %}

{% block body %}
  <div class="row">
    <h1> My Games </h1> <br>
    {% if object_list|length > 0 %}
      <div class="row">
        {% for game in object_list %}
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail alert-success">
              <div class="caption">
                <h3>Status: {% if game.status == "IP" %}Game In Progress{% elif game.status == "GO" %}Game Over{% elif game.status == "M"%}Waiting for a Player{% endif %}</h3>
                <p>
                  This game was created on {{ game.date }} <br>
                  {% if game.player1 %}
                    <b>First Player:</b> {{ game.player1.first_name }} <br>
                    <b>Score:</b> {{ game.player1_score }} <br>
                  {% endif %} <br>
                  {% if game.player2 %}
                    <b>Second Player:</b> {{ game.player2.first_name }} <br>
                    <b>Score:</b> {{ game.player2_score }} <br>
                  {% endif %} <br>
                </p>
                <p>
                  {% if game.status == "GO" and game.winner == request.user %}
                    Congratulations! You won this game! <br>
                  {% elif game.status == "GO" and game.winner != request.user %}
                    Sorry, you lost this game!
                  {% endif %}
                </p>
                <p>
                  {% if game.status == "IP" or game.status == "M" %}
                    <div align="center"><a href="{% url 'game' game.id %}" class="btn btn-primary" role="button">Resume</a></div> 
                  {% endif %}
                </p>
              </div>
            </div>
          </div>

        {% endfor %}
      </div>
    {% else %}
      You do not have any games.
    {% endif %}
  </div>
{% endblock %}

_16pawns/SixteenPawns/templates/invite.html
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Welcome to 16 pawns</title>

  <link href="style.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>

<body>


  <div class="container-fluid">
    <h1>Welcome to 16 pawns</h1>
    

	<div class="row">
		<div class="col-lg-12 text-center">
		<h3>Invite your friend</h3>
		<form>
			<div class="form-group">
                	<label class="sr-only" for="exampleInputEmail2">Enter Email address</label>
                	<input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" 				required>
             		</div>

			<div class="form-group">
                	<button type="submit" class="btn btn-primary btn-block">Invite</button>
             </div>
		</form>
		</div>
	</div>

</body>
</html>
         
<!--
       
          <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
             <div class="form-group">
                <label class="sr-only" for="exampleInputEmail2">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail2" placeholder="Email address" required>
             </div>
             <div class="form-group">
                <label class="sr-only" for="exampleInputPassword2">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password" required>
                                      <div class="help-block text-right"><a href="">Forget the password ?</a></div>
             </div>
             <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block">Sign in</button>
             </div>
             <div class="checkbox">
                <label>
                <input type="checkbox"> keep me logged-in
                </label>
             </div>
          </form>
       </div>
       <div class="bottom text-center">
        <h5> New here ? <a href="signup.html"><b>Join Us</b></a></h5>
       </div>
    </div>
</div>

_16pawns/SixteenPawns/templates/modal.html
<!-- Modal -->
<div class="modal fade" id="user_alert" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Game Info</h4>
      </div>
      <div class="modal-body" id="user_alert_body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

_16pawns/SixteenPawns/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head_extra %}
  <title>Welcome to 16 pawns</title>

  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

{% endblock %}

{% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1> Sign up!</h1>
      <form action="{% url 'signup' %}" method="post" class="form" role="form">
        {% csrf_token %}
        <div class="row">
          <div class="col-xs-6 col-md-6">
            {% if form.first_name.errors %}
              <ul>
                {% for error in form.first_name.errors %}
                  <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
              </ul>
            {% endif %}
            <input class="form-control" id="id_first_name" name="first_name" placeholder="First Name" type="text" required autofocus />
          </div>

          <div class="col-xs-6 col-md-6">
            <input class="form-control" id="id_last_name" name="last_name" placeholder="Last Name" type="text" required />
            {% if form.last_name.errors %}
              <ul>
                {% for error in form.last_name.errors %}
                  <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
              </ul>
            {% endif %}
          </div>
        </div>

        <input class="form-control" id="id_email" name="email" placeholder="Your Email" type="email" />
        <input class="form-control" id="id_email_cn" name="email_cn" placeholder="Re-enter Email" type="email" />
        {% if form.email.errors %}
          <ul>
            {% for error in form.email.errors %}
              <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
          </ul>
        {% endif %}

        <input class="form-control" id="id_password" name="password" placeholder="Password" type="password" />
        <input class="form-control" id="id_password_cn" name="password_cn" placeholder="Re-enter password" type="password" />
        {% if form.password.errors %}
          <ul>
            {% for error in form.password.errors %}
              <li><strong>{{ error|escape }}</strong></li>
            {% endfor %}
          </ul>
        {% endif %}

        <label class="radio-inline">
        <input type="radio" name="sex" id="inlineCheckbox2" value="proud" />
          Proud
        </label>
        <label class="radio-inline">
          <input type="radio" name="sex" id="inlineCheckbox1" value="male" />
          Male
        </label>
        <label class="radio-inline">
          <input type="radio" name="sex" id="inlineCheckbox2" value="female" />
          Female
        </label>

        <br />
        <br />
        <button id="id_sign_up" class="btn btn-lg btn-primary btn-block" type="submit">
          Sign up
        </button>
      </form>
    </div>
  </div>
</div>

{% endblock %}